# Generated by Django 3.0.8 on 2020-10-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': '3. Категория',
                'verbose_name_plural': '3. Категория',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='Telegram Id')),
                ('username', models.TextField(verbose_name='Telegram username')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
                ('count_buy', models.PositiveIntegerField(default=0, verbose_name='Кол-во покупок')),
                ('referral', models.PositiveIntegerField(default=0, verbose_name='Реферал')),
            ],
            options={
                'verbose_name': '1. Пользователь',
                'verbose_name_plural': '1. Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='usersmanage.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '4. Подкатегория',
                'verbose_name_plural': '4. Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35, verbose_name='Название товара')),
                ('product', models.TextField(help_text='Один товар - одна строчка', max_length=100000, verbose_name='Товар')),
                ('no_limit', models.BooleanField(default=False, help_text='Поставьте галочку если хотите чтобы товар был безлимитным', verbose_name='Безлимитный товар')),
                ('description', models.TextField(blank=True, help_text='Сюда писать описание товара', null=True, verbose_name='Описание товара')),
                ('subcategory', models.ForeignKey(help_text='Выберите подкатегорию', on_delete=django.db.models.deletion.CASCADE, to='usersmanage.SubCategory', verbose_name='подкатегория')),
            ],
            options={
                'verbose_name': '2. Товар',
                'verbose_name_plural': '2. Товары',
            },
        ),
    ]
