# Generated by Django 3.0.8 on 2020-10-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_p2p', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Токен P2P киви')),
                ('token_qiwi', models.TextField(max_length=300, verbose_name='Токен от киви')),
                ('number_qiwi', models.PositiveIntegerField(max_length=15, verbose_name='Номер киви без +')),
                ('start_text', models.TextField(max_length=1000, verbose_name='start текст')),
                ('help_text', models.TextField(max_length=1000, verbose_name='Текст кнопки помощь')),
            ],
            options={
                'verbose_name': '5. Настройка',
                'verbose_name_plural': '5. Настройки',
            },
        ),
    ]
