# Generated by Django 3.0.8 on 2020-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_auto_20201012_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsettings',
            options={'verbose_name': '5. Настройка бота', 'verbose_name_plural': '5. Настройки бота'},
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='start_text',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='help_text_en',
            field=models.TextField(default=12, help_text='Сюда писать текст для команды /start на английском', max_length=1000, verbose_name='Текст кнопки помощь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botsettings',
            name='help_text_ru',
            field=models.TextField(default=34, help_text='Сюда писать текст для команды /start на русском', max_length=1000, verbose_name='Текст кнопки помощь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botsettings',
            name='start_text_en',
            field=models.TextField(default=234, help_text='Сюда писать текст для команды /start на английском', max_length=1000, verbose_name='Текст для команды /start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botsettings',
            name='start_text_ru',
            field=models.TextField(default=23, help_text='Сюда писать текст для команды /start на английском', max_length=1000, verbose_name='Текст для команды /start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.TextField(default='ru', verbose_name='Язык'),
        ),
    ]
