# Generated by Django 3.0.8 on 2020-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0005_auto_20201013_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botsettings',
            old_name='help_text_ru',
            new_name='help_text',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='help_text_en',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='start_text_en',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='start_text_ru',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='start_text',
            field=models.TextField(blank=True, help_text='Сюда писать текст для команды /start на русском', max_length=1000, verbose_name='Текст для команды /start'),
        ),
    ]
