# Generated by Django 3.0.8 on 2020-10-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0006_auto_20201014_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=23, verbose_name='Стоимость товара'),
            preserve_default=False,
        ),
    ]
