# Generated by Django 3.0.8 on 2020-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_remove_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='admin_id',
            field=models.PositiveIntegerField(blank=True, help_text='Будет использован для уведомлений', null=True, verbose_name='id администратора'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='referral_percent',
            field=models.PositiveIntegerField(default=23, help_text='Общий реферальный % для всех пользователей', verbose_name='Реферальный %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referral_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Персональный реф %'),
        ),
    ]
