# Generated by Django 3.0.8 on 2020-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_auto_20201016_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='help_text',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='help_text_auto_guarantor',
            field=models.TextField(blank=True, help_text='Сюда писать текст для команды помощь в авто-гаранте', verbose_name='Текст кнопки помощь'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='help_text_shop',
            field=models.TextField(blank=True, help_text='Сюда писать текст для команды помощь в магазине', max_length=1000, verbose_name='Текст кнопки помощь'),
        ),
    ]
