# Generated by Django 3.0.8 on 2020-10-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0012_auto_20201016_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Реферал'),
        ),
    ]
