# Generated by Django 3.0.8 on 2020-10-17 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0013_auto_20201016_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма сделки')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв о продавце')),
                ('status', models.BooleanField(default=False, verbose_name='Статус сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='usersmanage.User', verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='usersmanage.User', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': '7. Сделка',
                'verbose_name_plural': '7. Сделки',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_rating', models.PositiveIntegerField(default=0, verbose_name='Положительный рейтнг')),
                ('bad_rating', models.PositiveIntegerField(default=0, verbose_name='Отрицательный рейтинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '6. Рейтинг пользователей',
                'verbose_name_plural': '6. Рейтинги пользователей',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
