# Generated by Django 3.0.8 on 2020-10-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0014_rating_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='bot_status',
            field=models.BooleanField(default=True, help_text='Если стоит галочка то бот включен, если нет то выключен', verbose_name='Статус бота'),
        ),
        migrations.AddField(
            model_name='trade',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий к сделке'),
        ),
        migrations.AddField(
            model_name='trade',
            name='start',
            field=models.BooleanField(default=False, verbose_name='Статус началась ли сделка'),
        ),
    ]
