# Generated by Django 3.0.8 on 2020-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0015_auto_20201017_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='seller',
        ),
        migrations.RenameField(
            model_name='botsettings',
            old_name='help_text_shop',
            new_name='help_text',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='help_text_auto_guarantor',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='number_qiwi',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='token_qiwi',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='address_btc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Адрес для платежей'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='token_btc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Токен BlockCypher'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
