# Generated by Django 3.1.2 on 2020-11-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0016_auto_20201022_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBuyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(verbose_name='Название товара')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '6. Последняя покупка',
                'verbose_name_plural': '6. Последнии покупки',
            },
        ),
    ]
