# Generated by Django 3.1.1 on 2020-11-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0019_auto_20201118_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglink',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersmanage.product', verbose_name='Товар'),
        ),
    ]
