# Generated by Django 3.1.2 on 2020-11-23 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0020_loglink_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbuyproduct',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 23, 10, 33, 19, 658103), verbose_name='Создан'),
        ),
    ]
