# Generated by Django 3.1.2 on 2020-11-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0022_auto_20201123_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbuyproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
