# Generated by Django 3.1.2 on 2020-11-23 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0024_auto_20201123_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbuyproduct',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
    ]
