# Generated by Django 3.1.2 on 2020-11-23 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0025_auto_20201123_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbuyproduct',
            name='create_date',
        ),
        migrations.AddField(
            model_name='allbuyproduct',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
